apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8tz
  namespace: argocd
spec:
  project: infra
  source:
    chart: k8tz
    repoURL: https://k8tz.github.io/k8tz/
    targetRevision: x.y.z # A patcher dans les overlays
    helm:
      releaseName: k8tz
      valuesObject:
        namespace: k8tz
        injectionStrategy: initContainer
        timezone: Europe/Paris
        injectAll: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: k8tz
  syncPolicy:
    automated:
      prune: true
